import mongoose, { Schema, Model} from 'mongoose';
import {Booking} from '../types';


//omit booking and created at because these will be auto generated by mongodb
export interface BookingDocument extends Omit<Booking, 'id' | 'createdAt'> {
    createdAt: Date;
}

//define schema
//we can create sub-schemas for user and slot to assign interfaces for further type safety
const bookingSchema = new Schema<BookingDocument>({
    user: {
        id: { type: String, required: true },
        name: { type: String, required: true },
        email: { type: String, required: true },
    },

    slot: {
        id: { type: String, required: true},
        date: { type: String, required: true},
        time: { type: String, required: true},
        isBooked: { type: Boolean, required: true, default: true}, //bookings are booked by default
    },

    createdAt: {type: Date, default: Date.now}, //default value is current date
})

// export model
export const BookingModel: Model<BookingDocument> =
    //check if model named "Booking" exists, if not create one
    mongoose.models.Booking || mongoose.model<BookingDocument>("Booking", bookingSchema);